language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - DEPENDENCY_INJECTION_VERSION=2.2.* EXPRESSION_LANGUAGE_VERSION=2.4.*
  - DEPENDENCY_INJECTION_VERSION=2.3.* EXPRESSION_LANGUAGE_VERSION=2.4.*
  - DEPENDENCY_INJECTION_VERSION=2.4.* EXPRESSION_LANGUAGE_VERSION=2.4.*
  - DEPENDENCY_INJECTION_VERSION=2.5.* EXPRESSION_LANGUAGE_VERSION=2.5.*
  - DEPENDENCY_INJECTION_VERSION=2.6.* EXPRESSION_LANGUAGE_VERSION=2.6.*
  - DEPENDENCY_INJECTION_VERSION=2.7.*@dev EXPRESSION_LANGUAGE_VERSION=2.7.*@dev
  - DEPENDENCY_INJECTION_VERSION=3.0.*@dev EXPRESSION_LANGUAGE_VERSION=3.0.*@dev

before_script:
  - composer require symfony/dependency-injection:${DEPENDENCY_INJECTION_VERSION}
  - composer require symfony/expression-language:${EXPRESSION_LANGUAGE_VERSION} --dev

notifications:
  email: matthiasnoback@gmail.com