language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.2.*
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.3.*
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.4.* EXPRESSION_LANGUAGE_VERSION=2.4.*
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.5.* EXPRESSION_LANGUAGE_VERSION=2.5.*
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.6.* EXPRESSION_LANGUAGE_VERSION=2.6.*
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=2.7.*@dev EXPRESSION_LANGUAGE_VERSION=2.7.*@dev
    - php: 5.6
      env: DEPENDENCY_INJECTION_VERSION=3.0.*@dev EXPRESSION_LANGUAGE_VERSION=3.0.*@dev

env:
  global:
    - DEPENDENCY_INJECTION_VERSION=""
    - EXPRESSION_LANGUAGE_VERSION=""

before_install:
  - if [ "$DEPENDENCY_INJECTION_VERSION" != "" ]; then composer require --dev --no-update symfony/dependency-injection "$DEPENDENCY_INJECTION_VERSION"; fi
  - if [ "$EXPRESSION_LANGUAGE_VERSION" != "" ]; then composer require --dev --no-update symfony/expression-language "$EXPRESSION_LANGUAGE_VERSION"; fi

install:
  - composer install --prefer-source

script:
  - vendor/bin/phpunit

notifications:
  email: matthiasnoback@gmail.com
